### ISSUE TITLE
something wrong with conda mirros

### ISSUE THREAD

**Issue by liuxiawei** [tuna/tunasync-scripts#163]
![图片](https://github.com/tuna/tunasync-scripts/assets/5093541/df1685fe-0b9c-4e97-9122-54225316bdd6)
I tried in different computer, and with conda, mamba, miniconda
20230707 10:40

**Comment by shankerwangmiao** [comment]
More detail information is needed. Please provide the whole configuration, the operation to reproduce the error and the complete output.

**Comment by liuxiawei** [comment]
```
anaconda/pkgs/main/noarch                           ??.?MB @  ??.?MB/s  0.5s
anaconda/pkgs/r/linux-64                                      No change
anaconda/pkgs/r/noarch                                        No change
anaconda/pkgs/msys2/linux-64                        ??.?MB @  ??.?MB/s  0.5s
anaconda/pkgs/msys2/noarch                                    No change
anaconda/pkgs/main/linux-64                          6.4MB @   1.9MB/s  3.5s
anaconda/cloud/bioconda/linux-64                     5.5MB @   1.4MB/s  3.5s
anaconda/cloud/bioconda/noarch                       4.7MB @   1.1MB/s  3.8s
conda-forge/noarch                                  14.3MB @   2.6MB/s  5.0s
conda-forge/linux-64                                36.0MB @   4.6MB/s  7.9s

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 936, in exception_converter
        raise e
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 930, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 888, in _wrapped_main
        result = do_call(args, p)
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 756, in do_call
        exit_code = update(args, parser)
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 646, in update
        return install(args, parser, "update")
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 497, in install
        index = load_channels(pool, channels, repos)
      File "${userpath}/Applications/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 178, in load_channels
        repo = subdir.create_repo(pool)
    RuntimeError: Could not read JSON repodata file (${userpath}/Applications/mambaforge/pkgs/cache/9cdf7780.json) parse error line 1

`$ ${userpath}/Applications/mambaforge/bin/mamba update --all`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=${userpath}/Applications/mambaforge:${userpath}/Applications/mambaforge/x8
                          6_64-conda-linux-gnu/sysroot/usr
   CONDA_BACKUP_JAVA_HOME=:-
CONDA_BACKUP_JAVA_LD_LIBRARY_PATH=:-
      CONDA_BUILD_SYSROOT=${userpath}/Applications/mambaforge/x86_64-conda-linux-gnu/sysroot
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=${userpath}/Applications/mambaforge/bin/conda
             CONDA_PREFIX=${userpath}/Applications/mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=${userpath}/Applications/mambaforge/bin/python
               CONDA_ROOT=${userpath}/Applications/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=${userpath}/Applications/mambaforge/lib/server
                     PATH=${userpath}/Applications/mambaforge/bin:${userpath}/.bun/bin:${userpath}/App
                          lications/mambaforge/bin:${userpath}/Applications/mambaforge/condabin:/${userpath}/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/
                          games
        QUARTO_SHARE_PATH=${userpath}/Applications/mambaforge/share/quarto
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
        UDUNITS2_XML_PATH=${userpath}/Applications/mambaforge/share/udunits/udunits2.xml
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session2

     active environment : base
    active env location : ${userpath}/Applications/mambaforge
            shell level : 1
       user config file : ${userpath}/.condarc
 populated config files : ${userpath}/Applications/mambaforge/.condarc
                          ${userpath}/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __linux=5.10.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : ${userpath}/Applications/mambaforge  (writable)
      conda av data dir : ${userpath}/Applications/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
          package cache : ${userpath}/Applications/mambaforge/pkgs
                          ${userpath}/.conda/pkgs
       envs directories : ${userpath}/Applications/mambaforge/envs
                          ${userpath}/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.28.2 CPython/3.10.8 Linux/5.10.0-23-amd64 debian/11 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

```
I reach it from Chengdu university of TCM. For the reported json file ,only the one line followed :
```
{"_cache_control":"","_etag":"\"6494895f-0\"","_mod":"Thu, 22 Jun 2023 17:48:15 GMT","_url":"https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/repodata.json",
```

**Comment by liuxiawei** [comment]
The command is `mamba update --all`. so as conda update

**Comment by shankerwangmiao** [comment]
It is not related with the sync scripts in this repo.
