### ISSUE TITLE
Anaconda: Installer sync failed

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/tunasync-scripts#87]
https://github.com/tuna/tunasync-scripts/blob/d5f2142cf20143efec33ac79ed91028bce049192/anaconda.py#L216

```
[2020-08-13 22:36:59,004] [INFO] Syncing installers...
[2020-08-13 22:36:59,005] [INFO] Start syncing https://repo.continuum.io/archive
[2020-08-13 22:37:01,967] [ERROR] Failed to sync installers of archive
Traceback (most recent call last):
  File "/home/scripts/anaconda.py", line 270, in main
    sync_installer(remote_url, local_dir)
  File "/home/scripts/anaconda.py", line 216, in sync_installer
    remote_filesize = int(r.headers['content-length'])
  File "/usr/local/lib/python3.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

ref: https://github.com/tuna/issues/issues/915

**Comment by holymonson** [comment]
这里加参数`allow_redirects=True`也许就可以了
https://github.com/tuna/tunasync-scripts/blob/d5f2142cf20143efec33ac79ed91028bce049192/anaconda.py#L199
